# Generated by Django 2.2.2 on 2019-09-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kart', '0002_auto_20190914_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='kart',
            name='products',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='kart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kart.Kart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
