# Generated by Django 2.2.2 on 2019-09-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kart', '0004_kart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
