# Generated by Django 2.2.2 on 2019-09-17 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kart', '0005_kart_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='accounts',
        ),
        migrations.AddField(
            model_name='kart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
