# Generated by Django 2.2.2 on 2019-09-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kart', '0008_kart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='kart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
