# Generated by Django 2.2.2 on 2019-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kart', '0011_cartitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
