# Generated by Django 2.2.2 on 2019-10-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190918_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shop',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
