# Generated by Django 2.2.2 on 2019-09-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_user'),
        ('order', '0007_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.RemoveField(
            model_name='history',
            name='quantity',
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.History')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
