# Generated by Django 2.2.2 on 2019-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190925_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Notstarted', 'Notstarted'), ('Started', 'Started'), ('Finished', 'Finished')], default='Notstarted', max_length=120),
        ),
    ]
