# Generated by Django 2.2.2 on 2019-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191001_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Notstarted', 'Notstarted'), ('Started', 'Started'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Notstarted', max_length=120),
        ),
    ]
