# Generated by Django 2.2.2 on 2019-10-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_user',
        ),
    ]
