# Generated by Django 2.2.2 on 2019-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20191002_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_user',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
