# Generated by Django 2.2.2 on 2019-10-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kart',
        ),
    ]
