# Generated by Django 2.2.2 on 2019-10-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_order_kart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
