# Generated by Django 2.2.2 on 2019-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_historyitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
