# Generated by Django 2.2.2 on 2019-10-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
