# Generated by Django 2.2.2 on 2019-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_image', models.ImageField(upload_to='product_img')),
                ('product_disc', models.TimeField()),
            ],
        ),
    ]
