# Generated by Django 2.2.2 on 2019-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_disc',
            field=models.TextField(),
        ),
    ]
